name: SF-detach

on: 
  workflow_dispatch:

env:
  DEPLOYMENT_NAME: SF-detach
  FlowHookName: "PreProxyFlowHook"

#   [
#     "PreProxyFlowHook",
#     "PostProxyFlowHook",
#     "PreTargetFlowHook",
#     "PostTargetFlowHook"
# ]

jobs:
  apigee-window-artifacts:
    name: SF-detach
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      # Configure Workload Identity Federation and generate an access token.
      - id: 'auth'
        name: 'Authenticate to Google Apigee Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          token_format: 'access_token'
          workload_identity_provider: '${{ secrets.WORKFLOW_IDENTITY_FEDERATION_NAME }}'
          service_account: '${{ secrets.GCP_SERVICE_ACCOUNT }}'
          
      - name: Set Git identity
        run: |
          git config --global user.email "rajeshjanapati533@gmail.com"
          git config --global user.name "pavansirasanambedu"

      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: SF-detach
        shell: pwsh
        run: |
          $env:flowhookname = $env:FlowHookName
          $env:TOKEN = "${{ steps.auth.outputs.access_token }}"          
          Invoke-Pester ./sf-detach.ps1 -Passthru
